Remove pickle dependency and add unit test for Tensorizer
coreweave/tensorizer pull request #3
Opened 2022-11-01 00:15 UTC by harubaru

I've also implemented a fallback to the `RequestsStreamFile` in case the user is running the tensorizer on a systems that aren't Unix-based since `CURLStreamFile` works with Unix dependencies.

2022-11-07 20:34 UTC, wbrown requested changes
Run this through `black -t 80` to resolve many of the line wrapping issues.

Some other minor comments.

2022-11-07 20:34 UTC, wbrown commented on tensorizer.py
> +from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig, CLIPTextModel, CLIPTokenizer, CLIPTextConfig
enclose in `()` and wrap to multiple lines.

2022-11-07 20:34 UTC, wbrown commented on tensorizer.py
> +from diffusers import AutoencoderKL, UNet2DConditionModel, StableDiffusionPipeline, LMSDiscreteScheduler
enclose in `()` and wrap to multiple lines.

2022-11-07 20:34 UTC, wbrown commented on tensorizer.py
> +                shapelist = self._read_shapes(headers[dtype_end + 1:(dtype_end + 1) + (4 * shape_len)], shape_len)
Wrap this.

2022-11-07 20:34 UTC, wbrown commented on tensorizer.py
>      # torch.save(y, f"{out_prefix}.state", _use_new_zipfile_serialization=False)
Remove these commented out lines of code.

2022-11-07 20:34 UTC, wbrown commented on tensorizer.py
> +        tensors_uri = f"{path_uri}/{model_prefix}tensors"
`.tensors` rather than `tensors`.

2022-11-07 20:34 UTC, wbrown commented on tensorizer.py
> +            os.path.dirname(path_uri), f"{model_prefix}config.json"
`-config.json` rather than `config.json`

2022-11-07 20:34 UTC, wbrown commented on tensorizer.py
> +        scheduler = LMSDiscreteScheduler(beta_end=0.012, beta_schedule="scaled_linear", beta_start=0.00085, num_train_timesteps=1000, trained_betas=None),
Wrap this line.

2022-11-10 19:51 UTC, arsenetar requested changes
Could we add a docstring or something in the README.md as to what the `hf_main()`, `df_main()`, `goose_main()`  are reference examples for (i.e. there are three different ones why/what is each one showing).  Think that makes them a better reference.

2022-11-10 20:14 UTC, harubaru commented
Sure, I can add that in. Should I leave `goose_main()` in also? I don't think it will work with the modifications made.

2022-11-15 19:08 UTC, wbrown approved these changes

2022-11-15 19:09 UTC, arsenetar approved these changes

2022-11-15 19:09 UTC, merged