perf(serialization) Reuse a pinned buffer when copying from gpu
coreweave/tensorizer pull request #98
Opened 2024-02-28 21:03 UTC by bchess

Similar to plaid mode, re-use one pinned buffer to handle the data transfer from GPU to CPU for serialization.

In main, serializing gpt-j-6B fp16 to nvme took 8.375s
In this branch, takes 4.796s

2024-02-28 22:44 UTC, wbrown commented
@bchess How does this affect tensors that are already on the CPU?

2024-02-29 00:23 UTC, Eta0 requested changes

2024-02-29 00:23 UTC, Eta0 commented on tensorizer/serialization.py
> +        biggest_tensor_bytes = max(t.nbytes for t in tensors)
`torch.Tensor.nbytes` is quite new (torch v2.1); this one will be more compatible, and we use it elsewhere in this file
```suggestion
        biggest_tensor_bytes = max(t.element_size() * t.nelement() for t in tensors)
```

2024-02-29 00:30 UTC, Eta0 approved these changes

2024-02-29 00:48 UTC, merged